### ISSUE TITLE
additional option to perform matching and scoring with unicode support

### ISSUE THREAD

**Issue by techgaun** [techgaun/zxcvbn-elixir#16]

**Comment by axelson** [comment]
Is it expected for ZXCVBN to raise an exception if provided a non-unicode string until this option is implemented?

Currently I see:
```
  test "unicode support" do
    password = "🏆🔥 and words"
    ZXCVBN.zxcvbn(password)
  end

     ** (UnicodeConversionError) incomplete encoding starting at <<240, 159>>
     code: ZXCVBN.zxcvbn(password)
     stacktrace:
       (elixir) lib/string.ex:2157: String.to_charlist/1
       (zxcvbn) lib/zxcvbn/matching.ex:565: anonymous fn/4 in ZXCVBN.Matching.do_sequence_match/2
       (elixir) lib/enum.ex:3003: Enum.reduce_range_inc/4
       (zxcvbn) lib/zxcvbn/matching.ex:561: ZXCVBN.Matching.do_sequence_match/2
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (zxcvbn) lib/zxcvbn/matching.ex:101: ZXCVBN.Matching.omnimatch/2
       (zxcvbn) lib/zxcvbn.ex:92: ZXCVBN.zxcvbn/2
       test/zxcvbn_test.exs:44: (test)
```

This test is with emoji but I believe it holds for foreign language characters as well.

**Comment by techgaun** [comment]
@axelson yep that's a known issue and is happening because it handles ASCII only at this time. I am working on getting support for this. I believe non-ASII passwords are used by very less percentage of people given the lack of support on various different platforms.

**Comment by axelson** [comment]
@techgaun any progress on this?

**Comment by techgaun** [comment]
@axelson I've added some support for this on master branch but need some time to do testing. Feel free to give master branch a try and see if that works in your case. I do need to spend some time to clean that up but I've not been finding time due to job and personal reasons for last few months.

**Comment by axelson** [comment]
Okay, I'll take a look at the version in master when I get a chance

**Comment by gmile** [comment]
FWIW, generally unicode appears to work nicely, but emojis are not handled still it seems:

![image](https://github.com/user-attachments/assets/1eba30b6-c3eb-4c36-8d0f-cf36d8f33fb9)
